--- #YAML:1.0
name:                POE-Component-IRC-Plugin-BaseWrap
version:             0.006
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          1.04
    POE:                           0.9999
    POE::Component::IRC::Plugin:   0.1
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
