---
name: POE-Component-IRC-Plugin-BaseWrap
version: 0.009
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: base class for IRC plugins which need triggers/ban/root control
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
requires:
  Carp: 1.04
  POE: 0.9999
  POE::Component::IRC::Plugin: 0.1
configure_requires:
  Module::Build: 0.35
provides:
  POE::Component::IRC::Plugin::BaseWrap:
    file: lib/POE/Component/IRC/Plugin/BaseWrap.pm
    version: 0.009
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
